# See https://wiki.hypr.land/Configuring/Keywords/
$terminal = uwsm app -- $TERMINAL
$menu = hyperion-menu
$browser = launch-browser
$mainMod = SUPER # Sets "Windows" key as main modifier

# Apps
bindd = $mainMod, return, Terminal, exec, $terminal
bindd = $mainMod SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = $mainMod, B, Browser, exec, $browser
bindd = $mainMod, N, Editor, exec, launch-editor

# Actions
bindd = $mainMod, W, Close active window, killactive,
bindd = , PRINT, Screenshot of region, exec, cmd-screenshot
bindd = SHIFT, PRINT, Screenshot of window, exec, cmd-screenshot window
bindd = CTRL, PRINT, Screenshot of display, exec, cmd-screenshot output

# Webapps
bindd = $mainMod, E, Email, exec, launch-webapp "https://mail.google.com"
bindd = $mainMod, A, ChatGPT, exec, launch-webapp "https://claude.ai"

# Containers
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bindd = $mainMod SHIFT, left, Swap window to the left, swapwindow, l
bindd = $mainMod SHIFT, right, Swap window to the right, swapwindow, r
bindd = $mainMod SHIFT, up, Swap window up, swapwindow, u
bindd = $mainMod SHIFT, down, Swap window down, swapwindow, d

# Floating
# Layout
bindd = $mainMod, J, Toggle window split, layoutmsg, togglesplit
bindd = $mainMod, P, Pseudo window, pseudo, # dwindle
bindd = $mainMod, T, Toggle window floating/tiling, togglefloating,
bindd = $mainMod, F, Full screen, fullscreen, 0 
bindd = $mainMod CTRL, F, Tiled full screen, fullscreenstate, 0 2
bindd = $mainMod ALT, F, Full width, fullscreen, 1

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Rofi
bindd = $mainMod, K, Show key bindings, exec, rofi-menu-keybindings
bindd = , Menu, Launcher, exec, $menu
bindd = $mainMod, space, Launcher, exec, rofi -show drun -theme ~/.config/rofi/themes/app-launcher.rasi
bindd = $mainMod, V, Clipboard manager, exec, cliphist list | rofi -dmenu -display-comlumns 2 | cliphist decode | wl-copy
bindd = , XF86PowerOff, Power Menu, exec, uwsm-app hyperion-menu system

# Session
bindd = $mainMod SHIFT, M, Exit, exit,

# Brightness control
bindel = , XF86MonBrightnessUp, exec, ~/.local/bin/brightness.sh up
bindel = , XF86MonBrightnessDown, exec, ~/.local/bin/brightness.sh down

# Volume Control
bindel = , XF86AudioRaiseVolume, exec, ~/.local/bin/volume.sh up
bindel = , XF86AudioLowerVolume, exec, ~/.local/bin/volume.sh down
bindl  = , XF86AudioMute, exec, ~/.local/bin/volume.sh mute

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

