# Floating windows
windowrule {
  name = windowrule-1
  float = on
  center = on
  size = 800 600
  match:tag = floating-window
}


windowrule {
  name = windowrule-2
  tag = +floating-window
  match:class = org.jsimpson.impala
}

windowrule {
    name = windowrule-btop
    tag = +floating-window
    match:class = org.jsimpson.btop
  }

windowrule {
  name = windowrule-3
  tag = +floating-window
  match:class = (xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus)
}

windowrule {
  name = windowrule-4
  tag = +floating-window
  match:title = (^Open Files?)
}



# Fullscreen screensaver
windowrule {
  name = windowrule-5
  fullscreen = on
  match:class = Screensaver
}


# No transparency on media windows
windowrule {
  name = windowrule-6
  opacity = 1 1
  match:class = ^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$
}

