# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- wl-paste --type text --watch cliphist store
exec-once = uwsm-app -- wl-paste --type image --watch cliphist store
exec-once = uwsm-app -- swaybg -i ~/.local/share/hyperion/themes/nord/background -m fill
