wallpaper {
    monitor = LVDS-1
    path = ~/.local/share/hyperion/current/theme/background
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.local/share/hyperion/current/theme/background
    fit_mode = cover
  }
