alias be='bundle exec'
alias g='git'
alias path=" tr ':' '\n' <<< '$PATH'"
alias rc='bin/rails console'
alias rdb='bin/rails dbconsole'
alias rdbm='bin/rails db:migrate && db:test:prepare'
alias rs='bin/rails server'
alias t='tmux'
alias v='nvim'
