export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=${HOME}/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:=${HOME}/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:=${HOME}/.local/share}
export XDG_STATE_HOME=${XDG_STATE_HOME:=${HOME}/.local/state}

export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle

# System variables to make folder XDG desktop compliant
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export _JAVA_OPTIONS=Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export PSQL_HISTORY="$XDG_DATA_HOME"/psql_history
export HISTFILE="$XDG_STATE_HOME"/zsh/history
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export LESSHISTFILE="$XDG_STATE_HOME"/less/history
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export ZDOTDIR=${ZDOTDIR:=${XDG_CONFIG_HOME}/zsh}
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export DOTNET_CLI_HOME="$XDG_DATA_HOME"/dotnet
export GOPATH="$XDG_DATA_HOME"/go
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NugetPackages
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup

export EDITOR=$(which nvim)
export BROWSER=/usr/bin/google-chrome-stable
export PAGER=less
export SHELL=/usr/bin/zsh

export SCREENSHOT="$HOME/Pictures"

# SYSTEM_PATH=$PATH
# unset PATH

# PATH=$PATH:$SYSTEM_PATH
# PATH=$PATH:$HOME/.local/bin
# export PATH

pathappend() {
  for ARG in "$@"
  do
    if [ -d "$ARG" ] && [[ ":$PATH:" != *":$ARG:"* ]]; then
        PATH="${PATH:+"$PATH:"}$ARG"
    fi
  done
}

pathprepend() {
  for ((i=$#; i>0; i--));
  do
    ARG=${!i}
    if [ -d "$ARG" ] && [[ ":$PATH:" != *":$ARG:"* ]]; then
        PATH="$ARG${PATH:+":$PATH"}"
    fi
  done
}

pathappend $HOME/.local/bin
pathappend $HOME/.local/share/npm/bin/
\npathappend $HOME/.local/share/applications
