export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=${HOME}/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:=${HOME}/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:=${HOME}/.local/share}
export XDG_STATE_HOME=${XDG_STATE_HOME:=${HOME}/.local/state}

# export GEM_HOME="$XDG_DATA_HOME"/gem
# export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem

export LESSHISTFILE="$XDG_STATE_HOME"/less/history

# export ZDOTDIR=${ZDOTDIR:=${XDG_CONFIG_HOME}/zsh}
# ZPLUG_HOME="$XDG_DATA_HOME/zplug"
# ZPLUG_LOADFILE="$XDG_CONFIG_HOME/zsh/plugins.zsh"
# ZPLUG_BIN='/usr/local/bin'
# ZPLUG_USE_CACHE=true
# ZPLUG_CACHE_DIR="$XDG_CACHE_HOME/zplug"

export EDITOR=$(which nvim)
export BROWSER=/usr/bin/google-chrome-stable
export PAGER=less
export SHELL=/usr/bin/zsh

SYSTEM_PATH=$PATH
unset PATH

PATH=$HOME/bin
PATH=$PATH:$HOME/.zsh/bin
PATH=$PATH:$SYSTEM_PATH
export PATH
