source ~/.zplug/init.zsh

zplug "mafredri/zsh-async", from:github
zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
zplug "zsh-users/zsh-autosuggestions", from:github

zplug load

for zsh_source in $HOME/.zsh/*.zsh; do
  source $zsh_source
done

export FZF_DEFAULT_COMMAND='rg --files --hidden'

bindkey -e # emacs bindings, set to -v for vi bindings

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
     [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
         eval "$("$BASE16_SHELL/profile_helper.sh")"

eval "$(zoxide init zsh)"

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=59'

source /usr/share/chruby/chruby.sh
source /usr/share/chruby/auto.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
