export EDITOR=vim
export TERMINAL=/usr/local/bin/st

export HISTFILE=~/.histfile
export HISTSIZE=100000
export SAVEHIST=$HISTSIZE

export FZF_DEFAULT_COMMAND='rg --files --hidden'

setopt SHARE_HISTORY

# Always start with 256 colors
[[ "$TERM" == "xterm" ]] && export TERM=xterm-256color

bindkey -e # emacs bindings, set to -v for vi bindings

# Completion
zstyle :compinstall filename '/home/jsimpson/.zshrc'

autoload -Uz compinit
compinit

# Adding themes to the prompt
autoload -Uz promptinit
promptinit

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
     [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
         eval "$("$BASE16_SHELL/profile_helper.sh")"

autoload -U colors && colors

alias gaa='git add --all'
alias gcam='git commit -a -m'
alias gco='git checkout'
alias gst='git status'
alias l='ls -lah'
alias ls='ls --color=tty'

setopt autocd autopushd pushdignoredups pushdsilent pushdminus          # .. is shortcut for cd .. (etc)

# Make completion:
# - Try exact (case-sensitive) match first.
# - Then fall back to case-insensitive.
# - Accept abbreviations after . or _ or - (ie. f.b -> foo.bar).
# - Substring complete (ie. bar -> foobar).
zstyle ':completion:*' matcher-list '' '+m:{[:lower:]}={[:upper:]}' '+m:{[:upper:]}={[:lower:]}' '+m:{_-}={-_}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

source ~/.zplug/init.zsh

zplug "mafredri/zsh-async", from:github
zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
zplug "zsh-users/zsh-autosuggestions", from:github

zplug load
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=59'

source /usr/share/chruby/chruby.sh
source /usr/share/chruby/auto.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
