source ~/Code/dotfiles/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=59'

fpath+=~/Code/dotfiles/zsh/plugins/pure
autoload -U promptinit; promptinit
prompt pure

for zsh_source in $HOME/.zsh/*.zsh; do
  source $zsh_source
done

export FZF_DEFAULT_COMMAND='rg --files --hidden'

bindkey -e # emacs bindings, set to -v for vi bindings

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
     [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
         eval "$("$BASE16_SHELL/profile_helper.sh")"

eval "$(zoxide init zsh)"


source /usr/share/chruby/chruby.sh
source /usr/share/chruby/auto.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
