#!/usr/bin/zsh

# There is a huge amount of discussion on this case on SO. The simplest most elegant
# solution appears to beto set it as an alias in .gitconfig.
#
# I'm not sure if it's POSIX compliant,or works with submodules.
#
# https://stackoverflow.com/a/23442470/3688634


function git() {
  if [ $# -eq 0 ]; then
    command git status
  elif [ "$1" = root ]; then
    shift
    local ROOT
    if [ "$(command git rev-parse --is-inside-git-dir 2> /dev/null)" = true ]; then
      if [ "$(command git rev-parse --is-bare-repository)" = true ]; then
        ROOT="$(command git rev-parse --absolute-git-dir)"
      else
        ROOT="$(command git rev-parse --git-dir)/.."
      fi
    else
      ROOT="$(command git rev-parse --show-superproject-working-tree 2> /dev/null)"
      if [ -z "$ROOT" ]; then
        ROOT="$(command git rev-parse --show-toplevel 2> /dev/null)"
      fi
    fi
    if [  -z "$ROOT" ]; then
      ROOT=.
    fi
    if [ $# -eq 0 ]; then
      cd "$ROOT"
    else
      (cd "$ROOT" && eval "$@")
    fi
  else
    command git "$@"
  fi
}

git $*
