#!/bin/bash
# First read all the positional parameters into an array
cmd_args=("$@")

# Sort the array
IFS=$'\n' sorted=($(sort <<<"${cmd_args[*]}"))
unset IFS

# The IFS part is setting the 'Internal Field Separator'
# https://unix.stackexchange.com/questions/184863/what-is-the-meaning-of-ifs-n-in-bash-scripting

# Now cycle through the array and print them out
for arg in "${sorted[@]}"; do
  echo "$arg"
done

