#!/usr/bin/zsh

emulate -LR zsh

path_name="$(basename "$PWD" | tr . -)"
session_name=${1-$path_name}

not_in_tmux() {
  [ -z "$TMUX" ]
}

# session_exists() {
#   tmux list-sessions | sed -E 's/:.*$//' | grep -q "^$session_name$"
# }

create_detached_session() {
  echo "(TMUX='' tmux new-session -Ad -s "$session_name")"
}

create_if_needed_and_attach() {
  if not_in_tmux; then
    echo "tmux new-session -As "$session_name""
  else
    # It seems that the command `if ! tmux has-session -t=$session_name 2> /dev/null; then`
    if ! tmux has-session -t=$session_name 2> /dev/null; then
      create_detached_session
    fi
    echo "tmux switch-client -t "$session_name""
  fi
}

create_if_needed_and_attach
